import { useState, useRef, useEffect } from "react";
import { MessageSquare, Send, X, Minimize2, Maximize2, Bot, User, Loader2 } from "lucide-react";
import { motion, AnimatePresence } from "motion/react";
import { cn } from "@/src/lib/utils";
import { GoogleGenAI } from "@google/genai";
import type { ArchitecturalDesign } from "@/src/services/gemini";

interface Message {
  role: "user" | "assistant";
  content: string;
}

interface ChatBotProps {
  currentDesign: ArchitecturalDesign | null;
  isOpen: boolean;
  setIsOpen: (open: boolean) => void;
}

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

export function ChatBot({ currentDesign, isOpen, setIsOpen }: ChatBotProps) {
  const [isMinimized, setIsMinimized] = useState(false);
  const [input, setInput] = useState("");
  const [messages, setMessages] = useState<Message[]>([
    { role: "assistant", content: "Hello! I'm your Archigen AI assistant. How can I help you with your architectural design today?" }
  ]);
  const [isLoading, setIsLoading] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  const handleSend = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!input.trim() || isLoading) return;

    const userMessage = input.trim();
    setInput("");
    setMessages(prev => [...prev, { role: "user", content: userMessage }]);
    setIsLoading(true);

    try {
      const context = currentDesign 
        ? `The user is currently viewing a design titled "${currentDesign.designOverview.concept}". 
           Layout Summary: ${currentDesign.designOverview.layoutSummary}. 
           Structural System: ${currentDesign.structuralRecommendations.constructionSystem}. 
           Sustainability: ${currentDesign.sustainabilityFeatures.environmentalImpact}.`
        : "The user has not generated a design yet.";

      const prompt = `
        You are an expert architectural assistant for the "Archigen AI" platform. 
        Your goal is to help clients understand architectural concepts, regulations, and the designs generated by this site.
        
        CONTEXT:
        ${context}
        
        USER QUESTION:
        ${userMessage}
        
        Provide a professional, helpful, and concise response. If the question is about a specific design, refer to the context provided.
      `;

      const response = await ai.models.generateContent({
        model: "gemini-3-flash-preview",
        contents: prompt,
      });

      setMessages(prev => [...prev, { role: "assistant", content: response.text || "I'm sorry, I couldn't process that request." }]);
    } catch (error) {
      console.error("Chat error:", error);
      setMessages(prev => [...prev, { role: "assistant", content: "I encountered an error. Please try again later." }]);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="fixed bottom-6 right-6 z-[100]">
      <AnimatePresence>
        {!isOpen && (
          <motion.button
            initial={{ scale: 0, opacity: 0 }}
            animate={{ scale: 1, opacity: 1 }}
            exit={{ scale: 0, opacity: 0 }}
            onClick={() => setIsOpen(true)}
            className="w-14 h-14 bg-ink text-bg rounded-full shadow-2xl flex items-center justify-center hover:bg-accent transition-colors group"
          >
            <MessageSquare className="w-6 h-6 group-hover:scale-110 transition-transform" />
          </motion.button>
        )}
      </AnimatePresence>

      <AnimatePresence>
        {isOpen && (
          <motion.div
            initial={{ y: 20, opacity: 0 }}
            animate={{ y: 0, opacity: 1 }}
            exit={{ y: 20, opacity: 0 }}
            className={cn(
              "technical-card bg-white shadow-2xl flex flex-col transition-all duration-300",
              isMinimized ? "h-14 w-64" : "h-[500px] w-[350px] md:w-[400px]"
            )}
          >
            {/* Header */}
            <div className="p-4 border-b border-line/10 flex items-center justify-between bg-ink text-bg">
              <div className="flex items-center gap-2">
                <Bot className="w-4 h-4" />
                <span className="text-[10px] font-mono uppercase tracking-widest font-bold">Archigen Assistant</span>
              </div>
              <div className="flex items-center gap-2">
                <button onClick={() => setIsMinimized(!isMinimized)} className="hover:opacity-70">
                  {isMinimized ? <Maximize2 className="w-3 h-3" /> : <Minimize2 className="w-3 h-3" />}
                </button>
                <button onClick={() => setIsOpen(false)} className="hover:opacity-70">
                  <X className="w-3 h-3" />
                </button>
              </div>
            </div>

            {!isMinimized && (
              <>
                {/* Messages */}
                <div className="flex-1 overflow-y-auto p-4 space-y-4 blueprint-grid">
                  {messages.map((msg, i) => (
                    <div
                      key={i}
                      className={cn(
                        "flex gap-3 max-w-[85%]",
                        msg.role === "user" ? "ml-auto flex-row-reverse" : ""
                      )}
                    >
                      <div className={cn(
                        "w-6 h-6 rounded-sm flex items-center justify-center shrink-0",
                        msg.role === "assistant" ? "bg-ink text-bg" : "bg-accent text-white"
                      )}>
                        {msg.role === "assistant" ? <Bot className="w-3 h-3" /> : <User className="w-3 h-3" />}
                      </div>
                      <div className={cn(
                        "p-3 text-xs leading-relaxed technical-border",
                        msg.role === "assistant" ? "bg-white" : "bg-accent/5"
                      )}>
                        {msg.content}
                      </div>
                    </div>
                  ))}
                  {isLoading && (
                    <div className="flex gap-3">
                      <div className="w-6 h-6 bg-ink text-bg rounded-sm flex items-center justify-center">
                        <Bot className="w-3 h-3" />
                      </div>
                      <div className="p-3 bg-white technical-border">
                        <Loader2 className="w-3 h-3 animate-spin opacity-40" />
                      </div>
                    </div>
                  )}
                  <div ref={messagesEndRef} />
                </div>

                {/* Input */}
                <form onSubmit={handleSend} className="p-4 border-t border-line/10 bg-white">
                  <div className="relative">
                    <input
                      type="text"
                      value={input}
                      onChange={(e) => setInput(e.target.value)}
                      placeholder="Ask a question..."
                      className="w-full pl-4 pr-10 py-2 bg-ink/5 border border-line/10 focus:border-accent outline-none text-xs font-sans"
                    />
                    <button
                      type="submit"
                      disabled={isLoading || !input.trim()}
                      className="absolute right-2 top-1/2 -translate-y-1/2 text-ink/40 hover:text-accent disabled:opacity-30 transition-colors"
                    >
                      <Send className="w-4 h-4" />
                    </button>
                  </div>
                </form>
              </>
            )}
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
